# Generated by Django 4.2.7 on 2023-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url_title',
            field=models.CharField(db_index=True, default='url-title', max_length=200, verbose_name='نام در url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
