# Generated by Django 4.2.7 on 2023-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_brand_url_title_alter_brand_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='ProductBrand',
        ),
    ]
