# Generated by Django 4.2.7 on 2023-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_brand_productbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, max_length=500, verbose_name='توضیحات اصلی'),
        ),
    ]
