# Generated by Django 4.2.7 on 2023-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, verbose_name='قیمت'),
        ),
    ]
