# Generated by Django 4.2.7 on 2023-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن درباره ما')),
                ('image', models.ImageField(upload_to='images/about-us', verbose_name='لوگو سایت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('number', models.IntegerField(verbose_name='تلفن تماس')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
            ],
        ),
    ]
