# Generated by Django 4.2.7 on 2023-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سایت'),
        ),
    ]
