# Generated by Django 4.2.7 on 2023-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_sitesettings_options_sitesettings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='number',
            field=models.CharField(max_length=200, verbose_name='تلفن تماس'),
        ),
    ]
