# Generated by Django 4.2.7 on 2023-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه ی لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصول'), ('about_us', 'صفحه ی درباره ما'), ('article_page', 'صفحه ی مقالات ')], max_length=200, verbose_name='محل استفاده'),
        ),
    ]
