# Generated by Django 4.2.7 on 2023-12-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_alter_sitebanner_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('sub_title', models.CharField(max_length=200, verbose_name='عنوان کوچک')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه اسلایدر')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='عکس اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدر های صفحه اصلی',
            },
        ),
    ]
