# Generated by Django 4.2.7 on 2023-12-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_siteslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteslider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
