# Generated by Django 5.0.6 on 2024-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمبل')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان تماس با ما')),
                ('message', models.TextField(verbose_name='متن تماس با ما')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('is_read_by_admin', models.BooleanField(blank=True, default=False, null=True, verbose_name='خوانده شده توسط ادمین')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'مجموع تماس با ما',
            },
        ),
    ]
