# Generated by Django 4.2.7 on 2023-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_remove_user_email_active_code_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
